# Generated by Django 4.2.2 on 2023-07-16 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_station_extra_services_station_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="owner_details",
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
